name: hugo
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
      - run: |
          HUGO_ENV=production hugo -D --minify; \
          git config --global user.name "${GITHUB_ACTOR}"; \
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"; \
          git add -f ./docs; \
          git commit -m "build"; \
          git push origin HEAD:${GITHUB_REF}; \
